### ISSUE TITLE
How to generate new spans?

### ISSUE THREAD

**Issue by luminoso** [mchlvl/starlette-zipkin#23]
Hello. Thank you for providing this middleware.

I'm using it and so far only faced one issue: how to generate new spanid for new requests?
For example:

Give that the initial outside request has:

```
x-b3-traceid: 507ef41245ec11d1ff205dc3927f09ea
x-b3-spanid: 2af3ad782dd31cc2
x-b3-parentspanid: f6ce15490ee720d8
```

Then `get_root_span().context`correctly computes the following:

```TraceContext(trace_id='507ef41245ec11d1ff205dc3927f09ea', parent_id='2af3ad782dd31cc2', span_id='3d280a67c6b78f0c', sampled=True, debug=False, shared=False)```

Which is fine.
What I can't seem to do is to do two calls in a row with two different span_id (or nowhere to generate a new one).

For example:

```python
async def i_am_handling_a_request():

    # we need to do one outside request
    async with httpx.AsyncClient() as client:
        headers = get_root_span().context.make_headers()
        response1 = await client.get(url="http://request1",
                                    headers=headers)
        print(response1)

    # and a new one
    async with httpx.AsyncClient() as client:
        headers = get_root_span().context.make_headers()
        response2 = await client.get(url="http://request2",
                                    headers=headers)
        print(response2)
```

Both `request1` and `request2` will have the same `spanid`, which if I'm not mistaken, should have different ones.

So, is there any better to generate a new child or should I patch the headers result from the `make_headers()` function?

**Comment by mardiros** [comment]
Hi  @luminoso 

You have to use the `trace` help to create span, the make headers is here to create a trace in the subservice.

```
from starlette_zipkin import trace


@trace('You can also do a parent trace here')
async def i_am_handling_a_request():

    # we need to do one outside request
    with trace("my request 1"):
        async with httpx.AsyncClient() as client:
            headers = trace.make_headers()
            response1 = await client.get(url="http://request1",
                                        headers=headers)
            print(response1)

    # and a new one
    with trace("my request 2"):
        async with httpx.AsyncClient() as client:
            headers = trace.make_headers()
            response2 = await client.get(url="http://request2",
                                        headers=headers)
            print(response2)
```

**Comment by mardiros** [comment]
You can get some inspiration from the example here:

https://github.com/mchlvl/starlette-zipkin/blob/master/examples/starlette/app/app.py

and there

https://github.com/mardiros/blacksmith/blob/master/src/blacksmith/middleware/_async/zipkin.py#L66-83

**Comment by luminoso** [comment]
Thank you! the links above pointed me in the right direction!

The only hiccup I had is when using the `@trace` decorator on a thread it losses the context and blows up.

Should a thread without a trace generate a new one? hum

**Comment by mardiros** [comment]
Honnestly, I never use threads here.

But actually, it use ContextVar, so, it should be thread safe.

See https://github.com/mchlvl/starlette-zipkin/blob/master/starlette_zipkin/trace.py#L16

See https://docs.python.org/3/library/contextvars.html

**Comment by mchlvl** [comment]
Afaik, e.g. `threading.Thead` does pass the context vars to the threads, but e.g. `concurrent.futures.ThreadPoolExecutor` doesnt. I quickly checked and it seems in Starlette's case, context info seems lost even with `threading.Thead`

One solution is to pass the context values to the threads and "set" the context variables once more ([example](https://kobybass.medium.com/python-contextvars-and-multithreading-faa33dbe953d)). It is sort of possible to get done with current codebase, e.g.:

```python
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route
from starlette_zipkin import (
    ZipkinMiddleware,
    get_tracer,
    trace,
)
from starlette_zipkin.trace import (
    _tracer_ctx_var,
    _cur_span_ctx_var,
)
import threading
import time


def inside_thread(tracer, span, id):
    print(f"id={id} started")
    # Set context vars again within the thread
    _tracer_ctx_var.set(tracer)
    _cur_span_ctx_var.set(span._span)
    with trace("awesome api sub trace 2") as child_span:
        headers = child_span.make_headers()
        print(f"id={id} generated headers {headers}")
        time.sleep(2)
        headers = child_span.make_headers()
        print(f"id={id} generated headers again {headers}")
    print(f"id={id} finished")


def run_with_threading(span):
    threads = []
    for i in range(3):
        t = threading.Thread(
                target=inside_thread,
                kwargs=dict(
                    tracer=get_tracer(),
                    span=span,
                    id=i
                )
            )
        threads.append(t)
        t.start()
    for x in threads:
        x.join()


async def root(request):
    with trace("awesome api sub trace") as child_span:
        run_with_threading(child_span)
        return JSONResponse(
            {"root": child_span.make_headers()}, headers=child_span.make_headers()
        )


routes = [
    Route("/", JSONResponse({"status": "OK"})),
    Route("/root", root),
]

app = Starlette(debug=True, routes=routes)
app.add_middleware(ZipkinMiddleware)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info", reload=True)
```

Note: if the main usecase is to make calls to external services, you can consider using the running event loop and run these async (technically less overhead than threading)

**Comment by mardiros** [comment]
> 
> Note: if the main usecase is to make calls to external services, you can consider using the running event loop and run these async (technically less overhead than threading)

[asyncio.gather](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather) is your friend.
