### ISSUE TITLE
tests are soft complaning

### ISSUE THREAD

**Issue by mardiros** [mchlvl/starlette-zipkin#30]
@mardiros neat! I noted the tests are soft complaning, but I think that should not block the functionality, so lets get this in 🎉

_Originally posted by @mchlvl in https://github.com/mchlvl/starlette-zipkin/issues/28#issuecomment-1059600927_

**Comment by mchlvl** [comment]
solved in [PR](https://github.com/mchlvl/starlette-zipkin/pull/31)
